spring:
  data:
    mongodb:
      uri: mongodb+srv://hytejasvi:D06ufNxF3kKf17sj@cluster0.rdme7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation : true
# link to generate app password: https://myaccount.google.com/apppasswords
  mail:
    host: smtp.gmail.com
    port: 587
    username: put-your-mail@id.com
    password: put the generated password here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#logging:
#  level:
#    com:
#      hytejasvi:
#        journalApp: DEBUG

#Logging levels: trace--> Debug--> Info--> Warn --> error
#by default, info and below are enabled, we need to particularly enable the above levels if needed
# if we set logging level as debug, then debug and it's below levels are enabled / allowed.