spring:
  data:
    mongodb:
      uri: mongodb+srv://hytejasvi:D06ufNxF3kKf17sj@cluster0.rdme7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation : true

server:
  port: 8080
  servlet:
    context-path: /journal #our application will have to start with this followed by API signature